"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--l#eikxuqegpw=hg1^q3i&ch45e&+5+3hm!pw4u(p@%rb@6ahf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',       # Django REST Framework
    'corsheaders',          # CORS handling
    'api',  
    'vendors',
]    

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'wecaregermanpharma',
        'USER': 'zda_devenviron',
        'PASSWORD': '7XxqiZw391vCIl6MudTk',
        'HOST': 'zdotapps-devenviron.cvuouqwaej9d.ap-south-1.rds.amazonaws.com',
        'PORT': '3306',
        # Keep DB connections open for a short time to reduce churn and 1040 errors
        'CONN_MAX_AGE': 0,            # seconds (0 = close immediately, None = forever)
        'CONN_HEALTH_CHECKS': True,    # ping connection before using it
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'connect_timeout': 0,
        },
        #'ATOMIC_REQUESTS': True,   ✅ wrap each request in a transaction
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # React dev server URL
]

# If you use CSRF-protected views with cookies, also trust the dev origin
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
]

# Password hashing configuration
# Order matters: the first hasher is used for new passwords
# Argon2 is recommended, but requires installing 'argon2-cffi'.
# After installing, you can uncomment the Argon2 hasher below to make it primary.
PASSWORD_HASHERS = [
    # 'django.contrib.auth.hashers.Argon2PasswordHasher',  # Optional primary: requires argon2-cffi
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',        # PBKDF2 with SHA-256 (primary)
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',  # bcrypt (requires 'bcrypt' package)
    'django.contrib.auth.hashers.ScryptPasswordHasher',        # scrypt
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',    # PBKDF2 with SHA-1
]

# razorpay keys
RAZORPAY_KEY_ID='rzp_test_3HM3cOG18rWK8Y'
RAZORPAY_KEY_SECRET='3UUgAugQ5CYYF5yyjLdXnI68'